import sqlite3, pandas as pd, os
os.chdir(r"D:\career-projects\Stock_Screener")
conn = sqlite3.connect('stock_data.db')
print('=== Tables ===')
for t in conn.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall():
    cnt = conn.execute(f'SELECT COUNT(*) FROM {t[0]}').fetchone()[0]
    print(f'  {t[0]}: {cnt} rows')
print()
print('=== fundamental_reports sample ===')
df = pd.read_sql_query("SELECT ticker, period, report_date, financial_year, quarter, revenue, pat, eps, ebit, source, source_type, verification_status FROM fundamental_reports ORDER BY ticker, report_date DESC LIMIT 30", conn)
print(df.to_string() if not df.empty else 'EMPTY')
print()
print('=== TICKERS with reports ===')
df2 = pd.read_sql_query('SELECT DISTINCT ticker, source_type, COUNT(*) c FROM fundamental_reports GROUP BY ticker, source_type', conn)
print(df2.to_string() if not df2.empty else 'EMPTY')
print()
print('=== companies ===')
df3 = pd.read_sql_query('SELECT * FROM companies', conn)
print(df3.to_string() if not df3.empty else 'EMPTY')
print()
print('=== raw_filings ===')
df4 = pd.read_sql_query('SELECT * FROM raw_filings LIMIT 10', conn)
print(df4.to_string() if not df4.empty else 'EMPTY')
print()
print('=== fundamental_ttm ===')
df5 = pd.read_sql_query('SELECT * FROM fundamental_ttm', conn)
print(df5.to_string() if not df5.empty else 'EMPTY')
